name: Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "apps/public_www/**"
      - "backend/infrastructure/**"
  push:
    branches:
      - main
    paths:
      - "apps/public_www/**"
      - "backend/infrastructure/**"

jobs:
  lint-web:
    name: Lint Public Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: apps/public_www/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: apps/public_www

      - name: Run lint
        run: npm run lint --if-present
        working-directory: apps/public_www

  build-cdk:
    name: Build CDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: npm
          cache-dependency-path: backend/infrastructure/package-lock.json

      - name: Install CDK dependencies
        working-directory: backend/infrastructure
        run: npm ci

      - name: Build CDK
        working-directory: backend/infrastructure
        run: npm run build
